services:
  my_app:
    hostname: my-app
    build: .
  nginx:
    hostname: nginx-proxy
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/my-app.conf
    depends_on:
      - my_app
  grafana:
    hostname: Grafana-monitoring
    image: grafana/grafana:latest
    ports: 
      - "3000:3000"
    environment: 
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/loki.yaml
  node-exporter:
    hostname: node-exporter
    image: prom/node-exporter:latest
    volumes: 
    - /proc:/proc
    - /sys:/sys
    - /:/host
    command: 
    - '--path.rootfs=/host'
    
  promethues:
    hostname: prom
    image: prom/prometheus:latest
    ports: 
      - "9090:9090"
    volumes:
    - ./prom.yml:/etc/prometheus/prometheus.yml

